const TIMEZONE_FORMAT = "YYYY-MM-DDTh:mm:ssa[Z]";
const TWELVE_HOUR_TIME_FORMAT = "h:mma";
const TWELVE_HOUR_TIME_FORMAT_2 = "h:mm";

export { TIMEZONE_FORMAT, TWELVE_HOUR_TIME_FORMAT, TWELVE_HOUR_TIME_FORMAT_2 };
